using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace lab3
{
    // Add this partial method definition to ensure InitializeComponent exists for the designer
    partial class Thuchanh2
    {
        private void InitializeComponent()
        {
            // This method is usually auto-generated by the Windows Forms Designer.
            // If you are missing the designer file (Thuchanh2.Designer.cs), you should add it via the designer.
            // For now, this empty method will resolve the CS0103 error.
        }
    }
}
